test_that("ResourceTracker passing the process ID correctly", {
  tracker <- ResourceTracker$new()
  expect_equal(tracker$pid, Sys.getpid())
  expect_error(tracker$start(), "Resource tracker already running")
  tracker$wait_for_samples(1)
  expect_equal(tracker$n_samples, 1)
  expect_true(is.data.frame(tracker$system_metrics))
  expect_true(is.data.frame(tracker$process_metrics))
  expect_equal(tracker$process_metrics$pid[1], tracker$pid)
  expect_true(is.list(tracker$cloud_info))
  expect_true(is.list(tracker$server_info))
  expect_true(is.list(tracker$recommend_resources()))
  expect_true(is.list(tracker$recommend_server()))
  expect_true(is.list(tracker$stats()))
  r <- as.character(tracker$report())
  expect_true(is.character(r))
  expect_true(grepl("^<html>", r))
  # TODO reeanable the below check after 0.4.1 release
  # expect_true(grepl("from <code>R</code>", r))
  expect_true(nchar(r) > 1000)
})
