site_name: "SC Resource Tracker"
repo_url: https://github.com/spareCores/resource-tracker/
edit_uri: blob/main/docs/

extra:
  homepage: https://sparecores.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/spareCores
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/SpareCores
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/SpareCores
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SpareCores/

nav:
  - index.md
  - Integrations:
    - integrations/index.md
    - Standalone: integrations/standalone.md
    - Metaflow: integrations/metaflow.md
    - R: integrations/r.md
  - Changelog: CHANGELOG.md

theme:
  name: "material"
  logo: logo-horizontal.png
  favicon: logo-128x128.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - search.suggest
    - navigation.footer
    - optimize

plugins:
- search
- autorefs
- api-autonav:
    modules: 
      - 'src/resource_tracker'
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          show_source: true
          show_signature: true
          separate_signature: true
          show_root_heading: true
          show_signature_annotations: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          members_order: source
          group_by_category: false
          summary: true

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
